# Generated by Django 6.0.4 on 2026-04-18 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_employee_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Number_of_Projects',
            new_name='number_of_projects',
        ),
    ]
